music_app/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('music_apps.urls', namespace='music_apps')), 
    url(r'^users', include('user_app.urls', namespace='user_app')),
    
]

music_apps/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views
urlpatterns = [
    url(r'^$', views.index, name='index'),
    
    #Shows all albums
    url(r'^detail/$', views.detail, name='detail'),
    
    #Individual pages for Album
    url(r'^detail/(?P<album_id>\d+)/$', views.albums, name='albums'),
    
    url(r'^add_album/$', views.add_album, name='add_album'),
    
    url(r'^add_song/(?P<album_id>\d+)/$', views.add_song, name='add_song'),
    
    url(r'^edit_song/(?P<song_id>\d+)/$', views.edit_song, name='edit_song'),
    
]

user_app/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import login

from . import views
urlpatterns = [
   url(r'^login/$', login, {'template_name': 'user_app/login.html'},
		name='login'),
		
   url(r'^logout/$', views.logout_view, name='logout'),
   
   url(r'^register/$', views.register, name='register'),
   
]

music_apps/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User

class Album(models.Model):
	album = models.CharField(max_length=100)
	album_dp = models.TextField()
	artist = models.CharField(max_length=100)
	logo = models.FileField(max_length=100)
	owner = models.ForeignKey(User, on_delete=models.CASCADE)
    
	def __str__(self):
		return self.album 
		

class Song(models.Model):
	album = models.ForeignKey(Album, on_delete=models.CASCADE)
	song = models.CharField(max_length=100)
	song_url = models.CharField(max_length=150, default='Paste URL here')
	
	def __str__(self):
		return self.song 

user_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

music_apps/forms.py
from .models import Album, Song
from django import forms

class AlbumForm(forms.ModelForm):
	class Meta:
		model = Album
		fields = ['artist', 'album', 'album_dp']
		label = {'text':''}
		
class SongForm(forms.ModelForm):
	class Meta:	
		model = Song
		fields = ['song', 'song_url']
		label = {'text':''}
		widget = {'text': forms.Textarea(attrs={'cols':80})}

music_apps/views.py
from __future__ import unicode_literals
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from .forms import AlbumForm, SongForm
from .models import Album, Song

def index(request):
	return render(request, 'music_apps/index.html') 
	
@login_required	
def detail(request):
	album = Album.objects.filter(owner=request.user).order_by()
	context = {'album':album}
	return render(request, 'music_apps/detail.html', context)

@login_required
def albums(request, album_id):
	album = Album.objects.get(pk=album_id)
	if album.owner != request.user:
		raise 404
	song = album.song_set.order_by()
	context = {'album':album, 'song':song}
	return render(request, 'music_apps/album_id.html', context)

@login_required
def add_album(request):
	#New song for a particular album
	if request.method != 'POST':
		form = AlbumForm() 
	else:
		form = AlbumForm(data=request.POST)
		if form.is_valid():
			new_album = form.save(commit=False)
			new_album.owner = request.user
			new_album.save()
			return HttpResponseRedirect(reverse('music_apps:detail'))			
			
	context = {'form':form}
	return render(request, 'music_apps/add_album.html', context)
	
@login_required
def add_song(request, album_id):
	album = Album.objects.get(pk=album_id) 
	song = album.song_set.order_by()
	if request.method != 'POST':
		form = SongForm()
	else:
		form = SongForm(data=request.POST)
		if form.is_valid():
			new_song = form.save(commit=False)
			new_song.album = album
			new_song.save()
			return HttpResponseRedirect(reverse('music_apps:albums', args=[album_id]))
		
	context = {'album':album, 'form':form}
	return render(request, 'music_apps/add_song.html', context)
	
@login_required
def edit_song(request, song_id):
	song = Song.objects.get(pk=song_id)
	album = song.album
	if album.owner != request.user:
		raise 404
	if request.method != 'POST':
		form = SongForm(instance=song)
	else:
		form = SongForm(data=request.POST, instance=song)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('music_apps:albums', args=[album.id]))
			
	context = {'form':form, 'album':album, 'song':song}
	return render(request, 'music_apps/edit_song.html', context)
	

user_app/views.py
from __future__ import unicode_literals
from django.shortcuts import render
from django.conf.urls import url
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.forms import UserCreationForm

def logout_view(request):

	logout(request)
	return HttpResponseRedirect(reverse('music_apps:index'))
	
def register(request):
	if request.method != 'POST':
		form = UserCreationForm()
	else:
		form = UserCreationForm(data=request.POST)
		new_user = form.save()
		user_authenticate = authenticate(username=new_user.username, 
			password = request.POST['password1'])
		login(request, user_authenticate)
		return HttpResponseRedirect(reverse('music_apps:index'))

	context = {'form': form }
	return render(request, 'user_app/register.html', context)

music_apps/templates/music_apps/add_album.html
{% extends 'music_apps/base.html' %}

{% block content %}
<p> Add a new Album </p>
	<form action="{% url 'music_apps:add_album' %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name='submit'>Submit</button>
	</form>
{% endblock content %}

music_apps/templates/music_apps/add_song.html
{% extends 'music_apps/base.html' %}

{% block content %}
	<p>New Songs</p>
	<form action='{% url "music_apps:add_song" album.id %}' method='POST' >
		{% csrf_token %}
		{{ form.as_p }}
		<button name='submit'>Submit</button>
	</form>
{% endblock content %}

music_apps/templates/music_apps/album_edit.html
<form action='{% url "music_apps:album_edit" %}' method='POST'></a>
	{% csrf_token %}
	{{ form.as_p }}
	<button name="submit">Submit</button>
</form>

music_apps/templates/music_apps/album_id.html
{% extends 'music_apps/base.html' %}

{% block content %}
	<h1>Album: {{ album }} </h1>
	<ul>
 		{% for songs in song %}
 			<li>{{ songs }}
 			<br>
  			<a href="{% url 'music_apps:edit_song' songs.id %}">-Edit</a></li>
		{% endfor %}
		<br>
		<a href="{% url 'music_apps:add_song' album.id %}">Add song</a> 		
	</ul>

{% endblock content %}

music_apps/templates/music_apps/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MUSIC APP</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
</head>

<body>
	<!-- Nav bar - Home header -->
	<nav class="navbar navbar-inverse navbar-static-top">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type='button' class='navbar-toggle collapse'
					data-toggle='collapse' data-target='#nav'
					aria-expanded='false' aria-controls='navbar'>
				</button>
				<a class='navbar-brand' href="{% url 'music_apps:index' %}">Home</a>
			</div>
			
	<!-- Nav bar - Details -->
			<div id='nav' class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					{% if user.is_authenticated %}
						<li><a href="{% url 'music_apps:detail' %}">Details</a></li>
					{% else %}
						<h1></h1>
					{% endif %}
				</ul>
	<!-- Nav bar - UserLogin -->
				<ul class='nav navbar-nav navbar-right'>
					{% if user.is_authenticated %}
						<li><a>Hello, {{ user.username }}.</a></li>
						<li><a href="{% url 'user_app:logout' %}">Log out</a></li>
					{% else %}
						<li><a href="{% url 'user_app:login' %}">Log in</a></li>
						<li><a href="{% url 'user_app:register' %}">Register</a></li>
					{% endif %}
				</ul>
			</div>
		</div>
	</nav><!-- /.nav-collapse -->
	
	<div class='container'>
	<div class="page-header">
		{% block header %} {% endblock header %}
			</div>
			<div>
		{% block content %} {% endblock content %}
			</div>
			</div>
</body>
</html>

music_apps/templates/music_apps/detail.html
{% extends 'music_apps/base.html' %}

{% block content %}
<h1> 
Details Page:
</h1>

<p>
<ul>
	{% for albums in album %}
		<li><a href='{% url "music_apps:albums" albums.id %}'>{{ albums }}</a></li>	
	{% endfor %}
</ul>
	<a href="{% url 'music_apps:add_album' %}">Add album</a>
</p>
{% endblock content %}

music_apps/templates/music_apps/edit_song.html
{% extends 'music_apps/base.html' %}
{% block content %}
	<form action='{% url "music_apps:edit_song" song.id %}' method='POST'></a>
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">Submit</button>
	</form>
{% endblock content %}

music_apps/templates/music_apps/index.html
{% extends 'music_apps/base.html' %}

{% block header %}
	<div class='jumbotron' >
		<h2>'Ello Gov'nor</h2>
	</div>
{% endblock header %}

{% block content %}
	{% if user.is_authenticated %}
		<h2>
			<a href="{% url 'music_apps:add_album' %}">Add album</a>
		</h2>
	{% else %}
		<h2>
			<a href="{% url 'user_app:register' %}">Register, in order to make your own
			music library.</a>
		</h2>
	
	{% endif %}
	

{% endblock content %}

user_app/templates/user_app/login.html
{% extends 'music_apps/base.html' %}

{% load bootstrap3 %}

{% block header %}
	<h2>Log in to your account. </h2>
{% endblock header %}

{% block content %}
	<form method='post' action='{% url "user_app:login" %}' class='form'>
		{% csrf_token %}
		{% bootstrap_form form %}
	
	{% buttons %}
		<button name="submit" class='btn btn-primary'>Log in</button>
	{% endbuttons %}
	
	<input type='hidden' name='next' value='{% url "music_apps:index" %}' />
	</form> 
{% endblock content %}

user_app/templates/user_app/register.html
{% extends 'music_apps/base.html' %}
{% load bootstrap3 %}

{% block header %}
 
	<div class='jumbotron'> 
	<h2>Register </h2>
	</div>
 
{% endblock header %}

{% block content %}
	<form method='post' action='{% url "user_app:register" %} class='form'>
		{% csrf_token %}
		{% bootstrap_form form %}
	
		{% buttons %}
			<button name="register" class="btn btn-primary">Register</buttons>
		{% endbuttons %}
			<input type='hidden' name='next' value='{% url "music_apps:index" %}'/>
	</form>
{% endblock content %}